name: Terraform AWS Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      # Checkout o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o AWS CLI usando credenciais do IAM OIDC no GitHub
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>
          aws-region: us-east-1  # Ajuste para a sua região da AWS

      # Instala o Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Ou outra versão necessária

      # Inicializa o Terraform
      - name: Terraform Init
        run: terraform init

      # Verifica o plano do Terraform
      - name: Terraform Plan
        run: terraform plan

      # Aplica as mudanças do Terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      # Destroi a infraestrutura se necessário
      - name: Terraform Destroy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: terraform destroy -auto-approve
