name: Terraform AWS Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar variáveis de ambiente com secrets da AWS
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Instalar o Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Versão ajustável conforme necessário

      # Step: Verificar formatação do Terraform
      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: false  # Falha o build se o formato estiver errado

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # Executar o Terraform Plan se for um Pull Request
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      # Executar o Terraform Apply apenas se for um push na branch main
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
